#!/bin/bash
echo -ne $(cut -c1 | tr -d '\n')'\n' #or cut -c 1 | tr -d "\n" && echo #or cut -c 1 | tr -d '\n' && echo -ne '\n' #or cut -c 1 | paste -s | tr -d [[:blank:]] #or cut -c 1 | paste -s -d ''
